### ISSUE TITLE
Question about data generation script

### ISSUE THREAD

**Issue by utahboy3502** [facebookresearch/ears_dataset#6]
Hello.

First, thank you for sharing dataset to the community. 

I was reading the paper, and it seems like there are preprocessing codes to generate training, validation, and test data files.

I only found the source code for downloading the dataset.

Do you plan to share the preprocessing source code to generate dataset in a future?

**Comment by alexanderrichard** [comment]
You can find the benchmark generation scripts here:
https://github.com/sp-uhh/ears_benchmark

**Comment by utahboy3502** [comment]
Oh I missed it. Thanks!

BTW, this is another question.
Do you think I can use this dataset for bandwidth extension task or other speech restoration tasks if I modify it? (By generating noisy signals via distortion types instead of convolving with SNRs)

**Comment by alexanderrichard** [comment]
Sure. As long as it's for non-commercial use, you are free to use the dataset. Please just make sure that you cite the dataset paper and, if you release a modified version of the dataset, we ask that our dataset paper gets cited for every use of the derived dataset as well.
